import { Case } from "@shared/schema";

export const case001: Case = {
  id: "case001",
  title: "لغز انهيار شركة الأمل العقارية",
  briefing: {
    sender: "مجلس الإدارة",
    text: "مرحباً أيها المحقق. الوضع خطير للغاية. شركة الأمل العقارية - واحدة من أكبر الشركات في المنطقة - تعاني من انهيار مفاجئ في المبيعات بنسبة 40% خلال الأسبوعين الماضيين. الغريب أن هذا حدث بعد إطلاق حملة تسويقية ضخمة كلفتنا ملايين! كل قسم يلقي اللوم على الآخر. التسويق يقول إنهم حققوا أرقاماً قياسية، والمبيعات يشتكون من ضغط العمل، والتقنية يدّعون أن كل شيء يعمل بشكل مثالي. نحتاج عيناً محايدة تحلل البيانات وتكشف الحقيقة. مستقبل 200 موظف على المحك.",
  },
  resources: {
    initialTime: 100,
    initialTrust: 100,
  },
  hypotheses: [
    {
      id: "h1",
      title: "خلل في استهداف الحملة التسويقية",
      description: "الحملة التسويقية استهدفت الجمهور الخطأ - أشخاص لا يملكون القدرة الشرائية أو الاهتمام الحقيقي بالعقارات الفاخرة.",
      isCorrect: true,
      requiredSupportingEvidence: ["ev3", "ev6", "ev9"],
      minSupportingEvidenceCount: 3,
      feedbackIfChosen: "تحليل ممتاز! اكتشفت أن الحملة ركزت على الانتشار الفيروسي بدلاً من الاستهداف الدقيق، مما جلب آلاف الزوار غير المؤهلين.",
      feedbackIfEliminated: "انتبه! هذه الفرضية قد تكون أهم مما تظن. راجع بيانات العملاء بدقة.",
    },
    {
      id: "h2",
      title: "ضعف أداء فريق المبيعات",
      description: "فريق المبيعات غير قادر على التعامل مع الضغط الجديد أو فقد حماسه بسبب مشاكل داخلية.",
      isCorrect: false,
      requiredSupportingEvidence: ["ev4"],
      minSupportingEvidenceCount: 2,
      feedbackIfChosen: "تحليل غير دقيق. فريق المبيعات يعمل بجد، لكن المشكلة ليست في أدائهم - بل في نوعية العملاء القادمين إليهم.",
      feedbackIfEliminated: "قرار صائب. الأدلة تشير إلى أن الفريق يعمل بكفاءة رغم الظروف الصعبة.",
    },
    {
      id: "h3",
      title: "مشكلة تقنية في الموقع الإلكتروني",
      description: "خلل تقني يمنع العملاء من إتمام عمليات الشراء أو التواصل بشكل صحيح.",
      isCorrect: false,
      requiredSupportingEvidence: ["ev2"],
      minSupportingEvidenceCount: 2,
      feedbackIfChosen: "استنتاج خاطئ. الموقع يعمل بشكل طبيعي والمشكلة التقنية كانت بسيطة جداً ولم تؤثر على المبيعات.",
      feedbackIfEliminated: "صحيح. المشكلة التقنية كانت روتينية ولا علاقة لها بانهيار المبيعات.",
    },
    {
      id: "h4",
      title: "ركود السوق العقاري",
      description: "السوق العقاري بشكل عام يمر بفترة ركود اقتصادي أثرت على جميع الشركات.",
      isCorrect: false,
      requiredSupportingEvidence: ["ev7"],
      minSupportingEvidenceCount: 2,
      feedbackIfChosen: "تحليل سطحي. السوق يشهد ركوداً طفيفاً بنسبة 5% فقط، وهذا لا يفسر انهياراً بنسبة 40%.",
      feedbackIfEliminated: "ممتاز. الركود الطفيف في السوق لا يبرر هذا الانهيار الحاد.",
    },
  ],
  evidence: [
    {
      id: "ev1",
      title: "إيميل إطلاق الحملة التسويقية",
      description: "من: سارة (مديرة التسويق)\nإلى: الإدارة العليا\nالموضوع: انطلاق حملة 'أحلامك تبدأ من هنا'\n\nيسعدني إعلامكم أننا أطلقنا الحملة بنجاح على تيك توك وإنستغرام. نتوقع وصولاً غير مسبوق! استثمرنا 70% من الميزانية في تيك توك لأن التكلفة لكل نقرة أقل بـ 80% من المنصات الأخرى.",
      type: "email",
      cost: 5,
      isKey: false,
      supportedHypotheses: [],
      refutedHypotheses: [],
      isMisleading: true,
      strengthLevel: "weak",
    },
    {
      id: "ev2",
      title: "تقرير الصيانة التقنية",
      description: "تقرير فني: تمت صيانة روتينية للخادم يوم 3 أكتوبر. توقف الموقع لمدة 15 دقيقة فقط (2:00-2:15 صباحاً). جميع الأنظمة تعمل بكفاءة 99.8%.",
      type: "report",
      cost: 10,
      isKey: false,
      supportedHypotheses: [],
      refutedHypotheses: ["h3"],
      isMisleading: false,
      strengthLevel: "strong",
    },
    {
      id: "ev3",
      title: "تحليل معدل التحويل",
      description: "مقارنة الأداء:\n- قبل الحملة: 50 عميل محتمل → 5 صفقات (معدل تحويل 10%)\n- بعد الحملة: 450 عميل محتمل → 0.5 صفقة (معدل تحويل 0.1%)\n\nملاحظة: العدد الإجمالي للعملاء ارتفع 9 أضعاف لكن المبيعات الفعلية انهارت.",
      type: "report",
      cost: 15,
      isKey: true,
      supportedHypotheses: ["h1"],
      refutedHypotheses: ["h2"],
      isMisleading: false,
      strengthLevel: "strong",
    },
    {
      id: "ev4",
      title: "سجل مكالمات فريق المبيعات",
      description: "إحصائيات الأسبوع الماضي:\n- متوسط المكالمات اليومية: 85 مكالمة (ارتفاع من 25)\n- متوسط مدة المكالمة: 3 دقائق (انخفاض من 15 دقيقة)\n- شكاوى العملاء من عدم الرد: 12 شكوى",
      type: "report",
      cost: 10,
      isKey: false,
      supportedHypotheses: ["h2"],
      refutedHypotheses: [],
      isMisleading: true,
      strengthLevel: "weak",
    },
    {
      id: "ev5",
      title: "نص الإعلان الترويجي",
      description: "🔥 فيلات الأحلام - خصم 50% لفترة محدودة! 🔥\nاربح فرصة للسكن في فيلا فاخرة!\nسجّل الآن واحصل على هدية مجانية!\n#مسابقة #هدايا #فيلات_مجانية\n\n[ملاحظة: لا يوجد توضيح أن 'الهدية' هي كتيب معلومات فقط]",
      type: "document",
      cost: 10,
      isKey: true,
      supportedHypotheses: ["h1"],
      refutedHypotheses: [],
      isMisleading: false,
      strengthLevel: "medium",
    },
    {
      id: "ev6",
      title: "تحليل ديموغرافي للعملاء الجدد",
      description: "توزيع العملاء المحتملين الجدد:\n- الفئة العمرية 16-22: 67%\n- الفئة العمرية 23-30: 25%\n- الفئة العمرية 31+: 8%\n\nالمهن المسجلة:\n- طالب: 45%\n- بدون عمل: 22%\n- وظائف مبتدئة: 28%\n- مهنيين/رجال أعمال: 5%",
      type: "data",
      cost: 15,
      isKey: true,
      supportedHypotheses: ["h1"],
      refutedHypotheses: ["h2", "h3", "h4"],
      isMisleading: false,
      strengthLevel: "strong",
    },
    {
      id: "ev7",
      title: "تقرير السوق العقاري الشهري",
      description: "المؤشرات الاقتصادية - أكتوبر:\n- نمو السوق العقاري: -5% (ركود طفيف)\n- متوسط أسعار العقارات: مستقر\n- عدد الصفقات في المنطقة: انخفاض 7%\n- أداء المنافسين: مستقر مع تراجع طفيف",
      type: "report",
      cost: 5,
      isKey: false,
      supportedHypotheses: ["h4"],
      refutedHypotheses: [],
      isMisleading: true,
      strengthLevel: "weak",
    },
    {
      id: "ev8",
      title: "مذكرة الرئيس التنفيذي للتسويق",
      description: "إلى فريق التسويق:\nنحتاج أرقاماً كبيرة هذا الربع. الأولوية للانتشار والوعي بالعلامة التجارية. لا تقلقوا بشأن التفاصيل، المهم أن نكون في كل مكان!\n- CEO",
      type: "document",
      cost: 5,
      isKey: false,
      supportedHypotheses: ["h1"],
      refutedHypotheses: [],
      isMisleading: false,
      strengthLevel: "weak",
    },
    {
      id: "ev9",
      title: "تسجيل مكالمة مبيعات نموذجية",
      description: "نص المكالمة:\nالعميل: 'مرحباً، شفت إعلانكم على تيك توك. أنا طالب جامعي، هل فعلاً ممكن أفوز بفيلا؟'\nالموظف: 'أهلاً، الإعلان يتحدث عن خصم على الفيلات وليس هدية مجانية...'\nالعميل: 'بس كاتب مسابقة وهدايا! إيش السعر؟'\nالموظف: 'تبدأ من 2 مليون ريال'\nالعميل: 'هههه، باي!' *أغلق الخط*",
      type: "testimony",
      cost: 15,
      isKey: true,
      supportedHypotheses: ["h1"],
      refutedHypotheses: ["h2"],
      isMisleading: false,
      strengthLevel: "strong",
    },
    {
      id: "ev10",
      title: "إحصائيات أداء الموظفين",
      description: "تقييم أداء فريق المبيعات - الربع الثالث:\n- معدل رضا العملاء: 4.2/5 (ممتاز)\n- معدل إغلاق الصفقات: 12% (أعلى من المتوسط)\n- ساعات العمل الإضافية: +40% عن المعتاد\n- معدل الاستجابة: 2 دقيقة (ممتاز)",
      type: "report",
      cost: 10,
      isKey: false,
      supportedHypotheses: [],
      refutedHypotheses: ["h2"],
      isMisleading: false,
      strengthLevel: "medium",
    },
    {
      id: "ev11",
      title: "تقرير تحليلات الموقع",
      description: "Google Analytics - أكتوبر:\n- الزيارات: 50,000 (ارتفاع 900%)\n- معدل الارتداد: 89% (كان 35%)\n- متوسط وقت الجلسة: 45 ثانية (كان 8 دقائق)\n- مصدر الزيارات: 78% تيك توك",
      type: "data",
      cost: 10,
      isKey: true,
      supportedHypotheses: ["h1"],
      refutedHypotheses: ["h3"],
      isMisleading: false,
      strengthLevel: "medium",
    },
    {
      id: "ev12",
      title: "شكوى مجهولة المصدر",
      description: "رسالة مجهولة وصلت للإدارة:\n'فريق المبيعات يضيع وقته في الاستراحة ولا يرد على المكالمات. راقبوهم!'",
      type: "clue",
      cost: 5,
      isKey: false,
      supportedHypotheses: ["h2"],
      refutedHypotheses: [],
      isMisleading: true,
      strengthLevel: "weak",
    },
  ],
  dataSets: [
    {
      name: "سجل المبيعات والعملاء المحتملين",
      description: "يظهر عدد العملاء المحتملين والمبيعات الفعلية خلال أسبوعين - قبل وبعد إطلاق الحملة.",
      rows: [
        { id: 1, date: "2023-09-25", leads: 48, sales: 5, conversionRate: 10.4 },
        { id: 2, date: "2023-09-26", leads: 52, sales: 6, conversionRate: 11.5 },
        { id: 3, date: "2023-09-27", leads: 45, sales: 4, conversionRate: 8.9 },
        { id: 4, date: "2023-09-28", leads: 50, sales: 5, conversionRate: 10.0 },
        { id: 5, date: "2023-09-29", leads: 55, sales: 6, conversionRate: 10.9 },
        { id: 6, date: "2023-09-30", leads: 47, sales: 5, conversionRate: 10.6 },
        { id: 7, date: "2023-10-01", leads: 180, sales: 3, conversionRate: 1.7 },
        { id: 8, date: "2023-10-02", leads: 320, sales: 1, conversionRate: 0.3 },
        { id: 9, date: "2023-10-03", leads: 450, sales: 0, conversionRate: 0.0 },
        { id: 10, date: "2023-10-04", leads: 520, sales: 1, conversionRate: 0.2 },
        { id: 11, date: "2023-10-05", leads: 480, sales: 0, conversionRate: 0.0 },
        { id: 12, date: "2023-10-06", leads: 510, sales: 0, conversionRate: 0.0 },
      ],
    },
    {
      name: "توزيع ميزانية التسويق",
      description: "إنفاق الحملة على المنصات المختلفة ونتائج كل منصة.",
      rows: [
        { id: 1, channel: "TikTok", budget: 150000, clicks: 45000, leads: 2800, sales: 2 },
        { id: 2, channel: "Instagram", budget: 30000, clicks: 8000, leads: 400, sales: 3 },
        { id: 3, channel: "Google Ads", budget: 15000, clicks: 2000, leads: 150, sales: 4 },
        { id: 4, channel: "LinkedIn", budget: 5000, clicks: 300, leads: 50, sales: 3 },
      ],
    },
    {
      name: "مقارنة جودة العملاء",
      description: "تحليل جودة العملاء المحتملين من كل قناة تسويقية.",
      rows: [
        { id: 1, channel: "TikTok", avgAge: 19, qualifiedPercent: 3, avgIncome: 15000 },
        { id: 2, channel: "Instagram", avgAge: 26, qualifiedPercent: 18, avgIncome: 45000 },
        { id: 3, channel: "Google Ads", avgAge: 38, qualifiedPercent: 42, avgIncome: 120000 },
        { id: 4, channel: "LinkedIn", avgAge: 41, qualifiedPercent: 65, avgIncome: 180000 },
      ],
    },
  ],
  stakeholders: [
    {
      id: "s1",
      name: "سارة العمري",
      role: "مديرة التسويق",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop",
      personality: "متحمسة، تدافع عن قراراتها بشدة",
      hiddenAgenda: "تخشى أن يُكتشف خطؤها في اختيار المنصة",
      questions: [
        {
          id: "q1_1",
          text: "كيف تصفين أداء الحملة الأخيرة؟",
          response: "الحملة حققت نجاحاً باهراً! وصلنا لملايين المشاهدات وأصبحنا ترند على تيك توك. الأرقام تتحدث عن نفسها - 50,000 زيارة للموقع! هذا أعلى رقم في تاريخ الشركة.",
          cost: 10,
          hiddenMeaning: "تركز على أرقام الوصول وتتجاهل جودة العملاء",
          supportedHypotheses: [],
          refutedHypotheses: [],
        },
        {
          id: "q1_2",
          text: "من هو الجمهور المستهدف في الحملة؟",
          response: "استهدفنا شريحة واسعة لزيادة الوعي بالعلامة التجارية. في التسويق الحديث، الانتشار هو الأهم. لاحقاً يمكننا تصفية العملاء الجادين.",
          cost: 15,
          hiddenMeaning: "اعتراف ضمني بعدم الاستهداف الدقيق",
          supportedHypotheses: ["h1"],
          refutedHypotheses: [],
        },
        {
          id: "q1_3",
          text: "لماذا اخترتم تيك توك تحديداً؟",
          response: "التكلفة لكل نقرة على تيك توك 0.05 ريال مقارنة بـ 5 ريال على جوجل! هذا يعني أننا نحصل على 100 ضعف النقرات بنفس الميزانية. من الناحية الاقتصادية، هذا قرار عبقري.",
          cost: 10,
          hiddenMeaning: "التركيز على الكمية بدلاً من الجودة",
          supportedHypotheses: ["h1"],
          refutedHypotheses: [],
        },
        {
          id: "q1_4",
          text: "هل درست ملاءمة جمهور تيك توك لمنتجاتكم؟",
          response: "تيك توك هو المستقبل! كل الشركات الكبرى تتجه إليه. نحن نبني علاقة مع جيل المستقبل... سيشترون منا عندما يكبرون.",
          cost: 15,
          hiddenMeaning: "تبرير ضعيف يكشف عدم التخطيط المسبق",
          supportedHypotheses: ["h1"],
          refutedHypotheses: [],
        },
      ],
    },
    {
      id: "s2",
      name: "أحمد الغامدي",
      role: "مدير المبيعات",
      avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop",
      personality: "محبط، يشعر بالظلم",
      hiddenAgenda: "يريد إثبات أن المشكلة ليست في فريقه",
      questions: [
        {
          id: "q2_1",
          text: "لماذا انخفضت المبيعات في رأيك؟",
          response: "لا أعرف بالضبط! نحن نعمل ضعف ساعات العمل المعتادة. الهواتف لا تتوقف لكن... المكالمات مختلفة عن المعتاد.",
          cost: 10,
          hiddenMeaning: "يلاحظ تغيراً في نوعية العملاء دون تحديد السبب",
          supportedHypotheses: [],
          refutedHypotheses: ["h2"],
        },
        {
          id: "q2_2",
          text: "ما الذي تغير في المكالمات؟",
          response: "سابقاً كان العميل يسأل عن التفاصيل والتشطيبات والموقع. الآن معظم الأسئلة: 'هل هذي مسابقة؟ كيف أشارك؟ وين الجائزة؟' بعضهم أطفال والله!",
          cost: 15,
          hiddenMeaning: "دليل قوي على جودة العملاء السيئة",
          supportedHypotheses: ["h1"],
          refutedHypotheses: ["h2"],
        },
        {
          id: "q2_3",
          text: "هل هناك مشكلة في فريق المبيعات؟",
          response: "فريقي محترف جداً. معدل إغلاق الصفقات عندنا 12% - أعلى من المتوسط الوطني. لكن كيف أبيع فيلا بمليونين لطالب جامعي مصروفه 500 ريال؟",
          cost: 10,
          hiddenMeaning: "يؤكد كفاءة الفريق ويوضح المشكلة الحقيقية",
          supportedHypotheses: ["h1"],
          refutedHypotheses: ["h2"],
        },
        {
          id: "q2_4",
          text: "هل يمكن أن يكون الفريق غير مدرب على الضغط الجديد؟",
          response: "نتعامل مع ضغوط أكبر في موسم الصيف. المشكلة ليست الضغط - المشكلة أننا نضيع 8 ساعات يومياً على مكالمات لا تؤدي إلى شيء. هذا مُحبط.",
          cost: 10,
          hiddenMeaning: "ينفي مشكلة التدريب ويشير للسبب الحقيقي",
          supportedHypotheses: ["h1"],
          refutedHypotheses: ["h2"],
        },
      ],
    },
    {
      id: "s3",
      name: "خالد المنصور",
      role: "مدير تقنية المعلومات",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
      personality: "هادئ، تقني، يتحدث بالأرقام",
      hiddenAgenda: "لا شيء - يريد فقط إثبات براءة قسمه",
      questions: [
        {
          id: "q3_1",
          text: "هل هناك أي مشاكل تقنية في الموقع؟",
          response: "لا، الموقع يعمل بكفاءة 99.8%. آخر صيانة كانت روتينية لمدة 15 دقيقة في الساعة 2 صباحاً. لم نتلقَ أي شكاوى تقنية من العملاء.",
          cost: 10,
          hiddenMeaning: "ينفي وجود مشكلة تقنية بالأدلة",
          supportedHypotheses: [],
          refutedHypotheses: ["h3"],
        },
        {
          id: "q3_2",
          text: "ماذا تلاحظ في سلوك زوار الموقع؟",
          response: "شيء غريب يحدث. الزيارات ارتفعت 900% لكن الزوار لا يتصفحون! معدل الارتداد 89% - يعني معظمهم يدخل ويخرج خلال ثواني. كأنهم يبحثون عن شيء آخر.",
          cost: 15,
          hiddenMeaning: "يوفر دليلاً تقنياً على عدم ملاءمة الجمهور",
          supportedHypotheses: ["h1"],
          refutedHypotheses: ["h3"],
        },
        {
          id: "q3_3",
          text: "من أين يأتي معظم الزوار الجدد؟",
          response: "78% من تيك توك. الغريب أن زوار تيك توك يقضون 45 ثانية فقط، بينما زوار جوجل يقضون 8 دقائق في المتوسط. فرق كبير جداً.",
          cost: 10,
          hiddenMeaning: "مقارنة توضح الفرق بين جودة المصادر",
          supportedHypotheses: ["h1"],
          refutedHypotheses: [],
        },
      ],
    },
  ],
  solution: {
    correctHypothesisId: "h1",
    requiredEvidenceIds: ["ev3", "ev6", "ev9"],
    feedbackCorrect: "تحليل ممتاز أيها المحقق! اكتشفت السبب الحقيقي: الحملة التسويقية ركزت على الانتشار الفيروسي والأرقام الكبيرة بدلاً من استهداف العملاء المؤهلين. استخدام تيك توك مع إعلانات مضللة (مسابقة، هدايا) جذب آلاف المراهقين والطلاب الذين لا يملكون القدرة على شراء عقارات فاخرة. النتيجة: فريق المبيعات أُغرق بمكالمات عديمة الفائدة، وضاع الوقت والموارد.",
    feedbackIncorrect: "تحليلك يحتاج مراجعة. ركز على ربط الأدلة ببعضها - لاحظ العلاقة بين نوعية العملاء، مصدر الزيارات، ومحتوى الإعلانات.",
    detailedExplanation: "السلسلة الكاملة للمشكلة:\n1. الإدارة طلبت 'أرقاماً كبيرة' دون تحديد معايير الجودة\n2. التسويق اختار تيك توك للتكلفة المنخفضة دون دراسة الجمهور\n3. الإعلانات استخدمت أسلوب 'النقر المخادع' (مسابقة، هدايا)\n4. النتيجة: 67% من العملاء الجدد تحت 22 سنة، 45% طلاب\n5. فريق المبيعات المحترف لم يستطع تحويل جمهور غير مؤهل\n6. انهيار معدل التحويل من 10% إلى 0.1%",
  },
};
